# Generated by Django 5.1.6 on 2025-03-12 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0006_watchlist_average_rating_watchlist_number_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='number_rating',
        ),
    ]
